name: Feature Request
description: Suggest a new feature or enhancement for the Rural Connectivity Mapper
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use of the tool
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Data Collection & Measurement
        - Data Analysis & Reporting
        - Visualization & Mapping
        - CLI/User Interface
        - Data Import/Export
        - Provider Integration
        - Performance & Optimization
        - Testing & Quality Assurance
        - Documentation
        - Infrastructure & Deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: use-case
    attributes:
      label: Primary Use Case
      description: Who would benefit most from this feature?
      options:
        - Rural Expansion Planning
        - ISP Performance Benchmarking
        - Infrastructure ROI Modeling
        - Policy Advocacy
        - Academic Research
        - General Users
        - Developers/Contributors
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I've also thought about...
    validations:
      required: false

  - type: dropdown
    id: starlink-alignment
    attributes:
      label: Starlink 2026 Alignment
      description: Does this feature align with Starlink's 2026 expansion goals?
      options:
        - Not applicable
        - Yes - Supports 10M rural connections target
        - Yes - Enables 20-30% agricultural productivity gains
        - Yes - Improves connectivity measurement accuracy
        - Yes - Other alignment
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What are the expected benefits of this feature?
      placeholder: |
        - Benefit 1
        - Benefit 2
        - Benefit 3
    validations:
      required: false

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details (Optional)
      description: Any technical implementation ideas or requirements?
      placeholder: This could be implemented using...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples
      placeholder: Screenshots, links to similar features, etc.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: true
